export const BEFORE_ALL_GISTS = "BEFORE_ALL_GISTS";
export const ALL_GISTS_SUCCESS = "ALL_GISTS_SUCCESS";
export const ALL_GISTS_ERROR = "ALL_GISTS_ERROR";

export const BEFORE_SINGLE_GIST = "BEFORE_SINGLE_GIST";
export const SINGLE_GIST_SUCCESS = "SINGLE_GIST_SUCCESS";
export const SINGLE_GIST_ERROR = "SINGLE_GIST_ERROR";
